import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Hub() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Taco Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/taco.png" alt="Taco pic" width={62} height={62}/>
      </Head>

      <main className={styles.main}>
      <h1>Welcome to</h1>
        <h1 className={styles.title}>
          The <Link href="/restaurants">TACO</Link> Hub
        </h1>
        <p className={styles.description}>
        <Image src="/3tacos.jpg" alt="Tacos" width={300} height={275} />
        </p>
        <h3>Click Taco to Enter!</h3>        
      </main>

      
    </div>
  )
}
